[build]
  command = "yarn build"
  functions = "build-api"
  functionsSource = "src/api"
  publish = "public"
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = nodejs10.x
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
