#!/bin/sh

# bin/bootstrap: Resolve all dependencies that the application requires to run.

# Exit script if any commands return errors (if the exit with non-zero)
set -e

# Work from the app’s root directory
cd "$(dirname "$0")/.."

# Install Homebrew dependencies from Brewfile
# Then re/start any brew dependencies that have services
echo "==> Installing Homebrew dependencies…"
brew bundle
