#!/bin/sh

# bin/bootstrap: Resolve all dependencies that the application requires to run.

# Exit script if any commands return errors (if the exit with non-zero)
set -e

# Work from the app’s root directory
cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  echo "==> Installing Homebrew dependencies…"
  brew bundle
else
  # Install apt-get package.list
  # @inspiredby https://askubuntu.com/questions/252734
  echo "==> Installing apt-get dependencies…"
  sudo apt-get install $(awk '{print $1'} apt.package.list)
fi

# Read the Node version from .node-version file
node_version=`cat .nvmrc`

echo "==> Configuring nvm…"
export NVM_DIR="$HOME/.nvm"

# Load NVM
if [ -f "/usr/local/opt/nvm/nvm.sh" ]; then
  source "/usr/local/opt/nvm/nvm.sh"
elif [ -f "/usr/local/opt/nvm/nvm.sh"]; then
  # TODO change to linux path
  source ""
fi

# Install Node
echo "==> Installing Node: $node_version"
nvm install $node_version

# All done!
echo
echo
echo
echo "==> SUCCESS! Your development environment is now bootstrapped!"
